In [ ]:
#1. Importa el paquete NUMPY bajo el nombre np.

In [3]:
#[tu código aquí]
import numpy as np

In [6]:
#2. Imprime la versión de NUMPY y la configuración.

#[tu código aquí]

print(np.__version__)

1.26.4


In [9]:
#3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
a = np.random.rand(2,3,5)

In [12]:
# Desafío: hay al menos tres maneras fáciles que usan numpy para generar arrays aleatorios. ¿Cuántas formas puedes encontrar? 

#[tu código aquí]
#np.random.random(), np.random.rand() y np.random.randint()

#4. Imprime a.

#[tu código aquí]
print(a)

[[[0.32009975 0.46530671 0.08840066 0.38030947 0.85705006]
  [0.61966985 0.70786898 0.44077501 0.22976235 0.4124286 ]
  [0.94451717 0.00986782 0.78053398 0.72898728 0.63194911]]

 [[0.05040288 0.08562826 0.77256399 0.14276822 0.53449131]
  [0.19835618 0.90751386 0.39016975 0.51303562 0.39552909]
  [0.00854988 0.12376224 0.67299474 0.75770104 0.4782181 ]]]


In [15]:
#5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
#Asigna el array a la variable "b"

#[tu código aquí]

b = np.ones((5,2,3))


In [17]:
#6. Imprime b.

print (b)

#[tu código aquí]

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [20]:
#7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?


#[tu código aquí]
x = a.size==b.size
print(x)


True


In [23]:
#8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?

#[tu código aquí]
#No es posible porque tienen diferente estructura

In [26]:
#9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".

#[tu código aquí]
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [49]:
#10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?
d = (a + c)
print(d)

#Ahora funciona porque tienen la misma estructura 

#[tu código aquí]

[[[1.32009975 1.46530671 1.08840066 1.38030947 1.85705006]
  [1.61966985 1.70786898 1.44077501 1.22976235 1.4124286 ]
  [1.94451717 1.00986782 1.78053398 1.72898728 1.63194911]]

 [[1.05040288 1.08562826 1.77256399 1.14276822 1.53449131]
  [1.19835618 1.90751386 1.39016975 1.51303562 1.39552909]
  [1.00854988 1.12376224 1.67299474 1.75770104 1.4782181 ]]]


In [51]:
#11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

#[tu código aquí]
print(a)
print(d)

[[[0.32009975 0.46530671 0.08840066 0.38030947 0.85705006]
  [0.61966985 0.70786898 0.44077501 0.22976235 0.4124286 ]
  [0.94451717 0.00986782 0.78053398 0.72898728 0.63194911]]

 [[0.05040288 0.08562826 0.77256399 0.14276822 0.53449131]
  [0.19835618 0.90751386 0.39016975 0.51303562 0.39552909]
  [0.00854988 0.12376224 0.67299474 0.75770104 0.4782181 ]]]
[[[1.32009975 1.46530671 1.08840066 1.38030947 1.85705006]
  [1.61966985 1.70786898 1.44077501 1.22976235 1.4124286 ]
  [1.94451717 1.00986782 1.78053398 1.72898728 1.63194911]]

 [[1.05040288 1.08562826 1.77256399 1.14276822 1.53449131]
  [1.19835618 1.90751386 1.39016975 1.51303562 1.39552909]
  [1.00854988 1.12376224 1.67299474 1.75770104 1.4782181 ]]]


In [53]:
#12. Multiplica a y c. Asigna el resultado a e.

#[tu código aquí]
e = a*c

print(e)

[[[0.32009975 0.46530671 0.08840066 0.38030947 0.85705006]
  [0.61966985 0.70786898 0.44077501 0.22976235 0.4124286 ]
  [0.94451717 0.00986782 0.78053398 0.72898728 0.63194911]]

 [[0.05040288 0.08562826 0.77256399 0.14276822 0.53449131]
  [0.19835618 0.90751386 0.39016975 0.51303562 0.39552909]
  [0.00854988 0.12376224 0.67299474 0.75770104 0.4782181 ]]]


In [ ]:
#13. ¿Es e igual a a? ¿Por qué sí o por qué no?

#[tu código aquí]
#Sí 

In [55]:
#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"

#[tu código aquí]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.944517169444933
1.0085498768277343
1.4549737314677018


In [71]:
#15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.

#[tu código aquí]

f = np.empty(d.shape)
print(f)

[[[0.32009975 0.46530671 0.08840066 0.38030947 0.85705006]
  [0.61966985 0.70786898 0.44077501 0.22976235 0.4124286 ]
  [0.94451717 0.00986782 0.78053398 0.72898728 0.63194911]]

 [[0.05040288 0.08562826 0.77256399 0.14276822 0.53449131]
  [0.19835618 0.90751386 0.39016975 0.51303562 0.39552909]
  [0.00854988 0.12376224 0.67299474 0.75770104 0.4782181 ]]]


In [92]:
"""
#16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
Asigna 0 al valor correspondiente(s) en f para d_min en d.
Asigna 100 al valor correspondiente(s) en f para d_max en d.
Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.
Nota: no necesitas usar Numpy en esta pregunta.
"""

#[tu código aquí]

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & ( d < d_max)] = 75
f[(d == d_mean)] = 50
f[(d == d_min)] = 0
f[(d == d_max)] = 100

print(f)



[[[ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [100.  25.  75.  75.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  75.  25.]
  [  0.  25.  75.  75.  75.]]]


In [94]:
"""
#17. Imprime d y f. ¿Tienes el f esperado?
Por ejemplo, si tu d es:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Tu f debería ser:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

#[tu código aquí]

print (f)
print (d)


[[[ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [100.  25.  75.  75.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.  75.  25.  75.  25.]
  [  0.  25.  75.  75.  75.]]]
[[[1.32009975 1.46530671 1.08840066 1.38030947 1.85705006]
  [1.61966985 1.70786898 1.44077501 1.22976235 1.4124286 ]
  [1.94451717 1.00986782 1.78053398 1.72898728 1.63194911]]

 [[1.05040288 1.08562826 1.77256399 1.14276822 1.53449131]
  [1.19835618 1.90751386 1.39016975 1.51303562 1.39552909]
  [1.00854988 1.12376224 1.67299474 1.75770104 1.4782181 ]]]


In [96]:
"""
#18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena 
("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
De nuevo, no necesitas Numpy en esta pregunta.
"""

#[tu código aquí]
f2 = np.empty(d.shape, dtype=object)

f2[(d > d_min) & (d < d_mean)] = "A"
f2[(d > d_mean) & ( d < d_max)] = "B"
f2[(d == d_mean)] = "C"
f2[(d == d_min)] = "D"
f2[(d == d_max)] = "E"

print (f2)

#def etiquetar(valor):
    if valor == 0:
        return 'A'
    elif valor == 25:
        return 'B'
    elif valor == 50:
        return 'C'
    elif valor == 75:
        return 'D'
    else:
        return 'E'
        
#np.vectorize(): Convierte la función para que pueda aplicarse a cada elemento de la matriz.
#f=np.vectorize(etiquetar)(f)
#print(f)


[[['A' 'B' 'A' 'A' 'B']
  ['B' 'B' 'A' 'A' 'A']
  ['E' 'A' 'B' 'B' 'B']]

 [['A' 'A' 'B' 'A' 'B']
  ['A' 'B' 'A' 'B' 'A']
  ['D' 'A' 'B' 'B' 'B']]]
